services:
  anki:
    image: anki-sync-server-docker
    container_name: anki-sync-server
    restart: unless-stopped
    command: anki-sync-server
    environment:
      - PASSWORDS_HASHED=1
      - SYNC_USER1=${ANKI_USERNAME}:${ANKI_HASHED_PASSWORD}
      - SYNC_BASE=${ANKI_CONTAINER_DATA}
    ports:
      - "${ANKI_HOST_PORT}:8080"
    volumes:
      - ${ANKI_HOST_DATA}:${ANKI_CONTAINER_DATA}

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    environment:
      - NGINX_SSL_CERT=${SSL_CERTIFICATE_NAME}
      - NGINX_SSL_CERT_KEY=${SSL_CERTIFICATE_KEY_NAME}
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
      - NGINX_ROOT_DIR=${NGINX_ROOT_DIR_CONTAINER}
    ports:
      - "${NGINX_HTTP_LISTEN_PORT}:80"
      - "${NGINX_HTTPS_LISTEN_PORT}:443"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/templates:/etc/nginx/templates:ro
      - ${NGINX_ROOT_DIR_HOST}:${NGINX_ROOT_DIR_CONTAINER}:ro
      - ${NGINX_LOG_DIR_HOST}:${NGINX_LOG_DIR_CONTAINER}
      - ./certs:/etc/ssl:ro 
